# Generated by Django 4.2.5 on 2023-09-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productsinventory_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=16)),
                ('role', models.CharField(choices=[('Admin', 'Administrator'), ('Normal User', 'Normal User')], default='Normal User', max_length=20)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
