# Generated by Django 4.2.4 on 2023-09-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_collaborator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='client',
            new_name='clientID',
        ),
    ]
