# Generated by Django 4.2.4 on 2023-09-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_client_sales_clientid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetails',
            old_name='sale',
            new_name='saleID',
        ),
    ]
