# Generated by Django 4.2.4 on 2023-09-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_sale_salesdetails_saleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='clientID',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='salesdetails',
            old_name='saleID',
            new_name='sale',
        ),
    ]
