# Generated by Django 4.2.5 on 2023-09-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_clientid_sales_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinventory',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
